<?php

$basePath = dirname(__DIR__);

?>

paths:
  base: <?=$basePath?>
  # these must be relative to basePath incl. leading slashes
  md: /data/tao-user-guide/src
  distro: /data/tao-user-guide/distro
  trees: /data/tao-user-guide/trees
  assets: /data/tao-user-guide/assets
  resources: /data/tao-user-guide/resources

# each of these targets must correspond to a plugin
targets:
  - name: Website
    bin: /usr/local/bin/pandoc
  - name: Ebook
    bin:
  - name: Tao
    bin:
  - name: Wiki
    bin:

# distribution targets
platforms:
  - name: Wordpress
    params:
      uri: http://wordpress.dev/?json_route=
      login: admin
      password: admin
      tags: [ imported ]
      source: Website