<?php

$basePath = dirname(__DIR__);

?>

paths:
  base: <?=$basePath?>
  # these must be relative to basePath incl. leading slashes
  in: /md/src
  out: /distro

# each of these targets must correspond to a plugin
targets:
  - Website
  - Ebook
  - Tao
  - Wiki