<?php

$basePath = dirname(__DIR__);

?>

paths:
  base: <?=$basePath?>
  # these must be relative to basePath incl. leading slashes
  in: /data/md/src
  out: /data/distro
  trees: /data/trees

# each of these targets must correspond to a plugin
targets:
  - name: Website
    bin: /usr/local/bin/pandoc
  - name: Ebook
    bin:
  - name: Tao
    bin:
  - name: Wiki
    bin: